.circleci/config.yml
- Changed tagdev to tag sandbox (env var in circleci + references)
- re-added package installation
=> Fix deployment

force-app/main/default/flexipages/LightningService_UtilityBar.flexipage-meta.xml, force-app/main/default/globalValueSets/TAG_ActivityType.globalValueSet-meta.xml
Added IA fields and missing market acitity types on the global picklist
=> Added fields on Activity Type

.circleci/config.yml
delete non-packagable metadata
=> delete non-packagable metadata

force-app/main/REMOVE_should-not-be-deployed/profiles/Admin.profile-meta.xml, force-app/main/REMOVE_should-not-be-deployed/profiles/NAV Kontor.profile-meta.xml, force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml, force-app/main/default/layouts/Contact-TAG Contact Layout.layout-meta.xml, force-app/main/default/objectTranslations/Account-no/Account-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/TAG_IAOwner__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/TAG_InclusionOwner__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Contact-no/Contact-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Contact-no/TAG_Informed__c.fieldTranslation-meta.xml, force-app/main/default/objects/Contact/fields/TAG_Informed__c.field-meta.xml, force-app/main/default/objects/Contact/validationRules/Field_Tag_Informed_chekced_before_save.validationRule-meta.xml, force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
Added section and two existing fields to TAG Account layout
Updated fields on related list for contact on account
Added Contact informed on contact page layout
Added validation rule that contact informed has to be checked before save
=> Updates on contact and account

force-app/main/default/objects/Task/listViews/TAG_Mine_oppgaver_pne_og_utf_rte.listView-meta.xml
Added list view that shows my tasks open and compledted less then 30 days
=> Added list view on tasks

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml, force-app/main/default/objectTranslations/Account-no/TAG_Employer_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/TAG_Employer_Region__c.field-meta.xml, force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
ANd addet to tag account page, translation and persmission set
=> Added formula field Employer region

force-app/main/customOpportunity/classes/TAG_ContactFormWebService_main.cls, force-app/main/customOpportunity/classes/TAG_ContactFormWebService_mainTest.cls, force-app/main/default/flows/Opportunity.flow-meta.xml
When adding an account to an opt (ie., user did not add org.number to web form), the account is added to the contact as well.
=> Tag1226 add acc to contact

force-app/main/default/objectTranslations/TemporaryLayoff__c-no/TAG_NAV_unit_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/TemporaryLayoff__c/fields/TAG_NAV_unit_Region__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_permittering_midlertidig.permissionset-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_temporaryLayoffs.permissionset-meta.xml
Lagt til Nav Office Region, lagt til i permisssion sets og oversatt. 2 Commits (oversettelse i egen commit)
=> Newfields layoff

README.md, force-app/main/customOpportunity/classes/TAG_CustomOpportunityRoutingHandler.cls
- added badges
- new install process
=> Updated readme

force-app/main/default/objectTranslations/Activity-no/TAG_NoPersonInformation__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Activity-no/TAG_service__c.fieldTranslation-meta.xml, force-app/main/default/objects/Activity/fields/TAG_NoPersonInformation__c.field-meta.xml, force-app/main/default/objects/Task/fields/Description.field-meta.xml
Changed helptext on fieldname "No personsenstive infomation" and translation on field, updated text om Comment on Activity.
=> Changed fieldhelp on acitivty and translation

force-app/main/default/permissionsets/Arbeidsgiver_permittering_midlertidig.permissionset-meta.xml
Added permission to read field is my nav office on permset for temp layoffs
=> Added permission to read is my nav office

force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
Updated Tag Default to have access to industry
=> Updated permset

force-app/main/default/objects/TemporaryLayoff__c/fields/Type__c.field-meta.xml, force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
Updated colours to fixed on field type on temp layoff
=> Minorupdates

force-app/main/default/objectTranslations/TemporaryLayoff__c-no/TAG_Account_zip__c.fieldTranslation-meta.xml, force-app/main/default/objects/TemporaryLayoff__c/fields/TAG_Account_zip__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_permittering_midlertidig.permissionset-meta.xml, force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
Added Account Zip field, formula that gets Shipping Zip from account. Updated permset and translation.
=> Added field on Temp Layoff

force-app/main/default/objectTranslations/Activity-no/Running_User_Office__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Activity-no/TAG_Running_User_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/Activity/fields/TAG_Running_User_Region__c.field-meta.xml, force-app/main/default/objects/TemporaryLayoff__c/fields/TAG_Is_My_NAV_Region__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_permittering_midlertidig.permissionset-meta.xml, force-app/main/default/permissionsets/TAG_default.permissionset-meta.xml
Added my region forula field. Looks up to user region and checks returns true if the record is related to same region. Added to permset and translation.
=> Adde my Region

force-app/main/default/reportTypes/TAG_Permitteringsvarsler_med_konto_og_NAV_kontor.reportType-meta.xml
Added fields on customreport type so that they are available.
=> Added fields on custom reporttype

force-app/apps/base/reportTypes/TAG_Permitteringsvarsler_med_konto_og_NAV_kontor.reportType-meta.xml
Added field in report type for temp layoff
=> Added main industry to report type

force-app/main/default/objects/CustomOpportunity__c/fields/Is_My_NAV_Office__c.field-meta.xml
Update is my navoffice on custom opportunity
=> Updated formula filed

force-app/main/default/objects/CustomOpportunity__c/fields/Is_My_NAV_Office__c.field-meta.xml
=> Update mynavoffice opportunity

force-app/main/default/objects/CustomOpportunity__c/fields/Source__c.field-meta.xml, force-app/main/default/objects/CustomOpportunity__c/recordTypes/Inclusion.recordType-meta.xml, force-app/main/default/objects/CustomOpportunity__c/recordTypes/Inclusive_Employment.recordType-meta.xml
=> Added picklistvalue Custom Opp.

force-app/apps/base/permissionsets/Arbeidsgiver_opportunity.permissionset-meta.xml, force-app/apps/base/permissionsets/TAG_default.permissionset-meta.xml, force-app/main/customOpportunity/objectTranslations/CustomOpportunity__c-no/JsonPayload__c.fieldTranslation-meta.xml, force-app/main/customOpportunity/objectTranslations/CustomOpportunity__c-no/TAG_Is_my_NAV_region__c.fieldTranslation-meta.xml, force-app/main/customOpportunity/objectTranslations/CustomOpportunity__c-no/TAG_NAV_Unit_Region__c.fieldTranslation-meta.xml, force-app/main/customOpportunity/objectTranslations/CustomOpportunity__c-no/TAG_NavUnit__c.fieldTranslation-meta.xml, force-app/main/default/objects/CustomOpportunity__c/fields/TAG_Is_my_NAV_region__c.field-meta.xml, force-app/main/default/objects/CustomOpportunity__c/fields/TAG_NAV_Unit_Region__c.field-meta.xml
Added formula field for NAV Office Region and is my NAV Office region, with translation and permsets
=> Added Formula fields on custom opportunity

force-app/main/default/prompts/tag_Nykildepmulighet.prompt-meta.xml
In app guidance for custom opportunity, adde kilde
=> Adde in app guidance

force-app/apps/base/flexipages/TAG_DefaultHomePage.flexipage-meta.xml, force-app/main/default/objects/CustomOpportunity__c/listViews/Mitt_NAV_kontor_Nye.listView-meta.xml
Updated and added listview for Muligheter on homescreen
=> Updated listview homepage

force-app/main/default/objectTranslations/TemporaryLayoff__c-no/Account__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/TemporaryLayoff__c-no/NAV_Unit__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/TemporaryLayoff__c-no/TAG_Is_My_NAV_Region__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/TemporaryLayoff__c-no/TemporaryLayoff__c-no.objectTranslation-meta.xml
Endret navn til Varsel til NAV
=> Endert oversettelse på templ layoff

force-app/apps/base/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
=> Updated arbeidgiver base permset

force-app/main/customOpportunity/layouts/CustomOpportunity__c-Inclusion Page Layout.layout-meta.xml
Updated pagalayout for inclusion recordtype.
=> Pagelayout Cutom opportunity

force-app/main/customOpportunity/layouts/CustomOpportunity__c-Inclusion Page Layout.layout-meta.xml, force-app/main/customOpportunity/objectTranslations/CustomOpportunity__c-no/CustomOpportunity__c-no.objectTranslation-meta.xml, force-app/main/default/objects/CustomOpportunity__c/validationRules/No_person_information_added.validationRule-meta.xml
Updated validation rule to only run if short desc. is not empty and removed some fields from pagelayout
=> Simple opportunity pagalayout ass

.github/workflows/deploy-to-dev.yml, .github/workflows/validation.yml, force-app/apps/base/layouts/Account-TAG Virksomhet.layout-meta.xml
Added source field on accountpagelayout for custom opp
=> Added source custom opp on account

force-app/apps/base/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/objectTranslations/Contract__c-no/Contract__c-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Contract__c-no/TAG_Opportunity__c.fieldTranslation-meta.xml
Endret oversettelse av avtale til bedriftsavtale
=> Endret oversettelse av avtale til bedriftsavtale

force-app/apps/base/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/apps/base/layouts/Account-TAG Virksomhet.layout-meta.xml
Changed contact listwiew on account to enhanced and added phone column
=> Added phone to contact list

force-app/apps/base/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/apps/base/layouts/Account-TAG Virksomhet.layout-meta.xml
=> Legge til telefon kontaktvisning

force-app/apps/base/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/objects/Contact/fields/SourceFormula__c.field-meta.xml
Updated source field on contact to "Varsel til NAV" (old permittering)
Changed name tab on account form Permittering to Varsel
=> Update on Account and Contact

force-app/main/default/objects/ArenaActivity__c/ArenaActivity__c.object-meta.xml
Added report to true on Arene Act object
=> Set report on arena acitivty

force-app/functionality/customOpportunity/layouts/CustomOpportunity__c-Inclusion Page Layout.layout-meta.xml
Made NAV Unit mandatory on pagelayout for inclusion
=> NAV Unit mandatory on Cust Opp

force-app/main/default/permissionsetgroups/Arbeidsgiver_Base_Group.permissionsetgroup-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_opportunity.permissionset-meta.xml
Included permission for OwnerFullname
=> Updated permission set Custom Opportunity

force-app/main/default/permissionsets/Arbeidsgiver_opportunity.permissionset-meta.xml
Removed access to IA recordtype
=> Updatet permset custom opp

force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Access to unit on task and activity
=> Updated arebeidsgiver base permisseion

force-app/main/default/objects/Contact/fields/InvalidEmail__c.field-meta.xml, force-app/main/default/objects/Contact/fields/TAG_Informed__c.field-meta.xml
- Altered help text in Contact Infomed field
- Altered help text in Ugyldig e-postadresse field + Altered description field
=> Edited help text in two fields in Contact object

force-app/functionality/customOpportunity/flows/Opportunity.flow-meta.xml
- Added criteria Contact field can not be null, for process to execute
=> New version of Opportunity insert/update process

force-app/functionality/customOpportunity/flows/Opportunity.flow-meta.xml
This reverts commit 84b6d4419e3a4b3c31753bee05343aad6161f33e.
=> Revert "New version of Opportunity insert/update process"

force-app/functionality/customOpportunity/flows/Opportunity.flow-meta.xml
- Added criteria Contact field can not be null, for process to execute
=> New version of process Opportunity insert/update

force-app/main/default/prompts/Oppdateringavprofflink.prompt-meta.xml
In app guidance on updates to proff.no link
=> In-App guidance proff.no

force-app/main/default/flexipages/TAG_DefaultHomePage.flexipage-meta.xml
Added rich text field for Nytt og Nyttig
=> Updated section homempage tag

force-app/main/default/permissionsetgroups/Arbeidsgiver_Base_Group.permissionsetgroup-meta.xml
Added Arbedigsgiver Arene Permset to Arbeidsgiver base group
=> Added arena permset to base

force-app/functionality/arenaActivity/layouts/ArenaActivity__c-Arena Aktivitet Layout.layout-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_arenaActivity.permissionset-meta.xml
Fjernet tilgang til Beskrivelse på Arena aktiviteter fra arena perm set og fra pagelayout.
=> Fjernet tilgang til Beskrivelse Arena Akt

force-app/main/default/flexipages/TAG_ContactRecordPage.flexipage-meta.xml
To include related accounts on first page of Accounts and removed tab
=> Updated contact page

force-app/functionality/customOpportunity/layouts/CustomOpportunity__c-Inclusion Page Layout.layout-meta.xml, force-app/functionality/customOpportunity/layouts/CustomOpportunity__c-Inclusive Employment Page Layout.layout-meta.xml, force-app/functionality/customOpportunity/objectTranslations/CustomOpportunity__c-no/Profession__c.fieldTranslation-meta.xml, force-app/main/default/layouts/CustomOpportunity__c-Simple Opp Layout.layout-meta.xml, force-app/main/default/objects/CustomOpportunity__c/fields/Profession__c.field-meta.xml
- Translated Profession to Yrke
- Edited page layout for Custom opportunity
=> Created Profession field on Custom opportunity

force-app/main/default/objectTranslations/Account-no/Account-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/Is_My_NAV_Office__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/Is_My_NAV_Region__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/NAV_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/Is_My_NAV_Office__c.field-meta.xml, force-app/main/default/objects/Account/fields/Is_My_NAV_Region__c.field-meta.xml, force-app/main/default/objects/Account/fields/NAV_Region__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added 3 formula fields for is my nav office, region and NAV region to show region on account
=> IS my NAV office and region Account

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml, force-app/main/default/objectTranslations/Account-no/Account-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/Alias__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/EditableEmail__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/EditablePhone__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/EditableWebsite__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/Alias__c.field-meta.xml, force-app/main/default/objects/Account/fields/EditableEmail__c.field-meta.xml, force-app/main/default/objects/Account/fields/EditablePhone__c.field-meta.xml, force-app/main/default/objects/Account/fields/EditableWebsite__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Pilot_for_nye_kontofelter.permissionset-meta.xml
- Added fields Alias, EditablePhone, EditableEmail and EditableWebsite to Account
- Translations
- New permission set for the fields
=> Added new fields to the Account object

force-app/main/default/objectTranslations/NavTask__c-no/CRM_AccountRelated__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/NavTask__c-no/CRM_Account__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/NavTask__c-no/CRM_NavUnit__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/NavTask__c-no/NavTask__c-no.objectTranslation-meta.xml, force-app/main/default/objects/NavTask__c/listViews/Mine_NAV_Oppgaver.listView-meta.xml
- Edited list translation
- Edited translation for related objects
=> Edit translations for NAV task object

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
- Update perm set
- Update Page Layout
=> Publish new Account fields to all users

force-app/main/default/permissionsets/Arbeidsgiver_opportunity.permissionset-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_temporaryLayoffs.permissionset-meta.xml
Added access to NAV Market Region field on permset mulighet  and permittering
=> Access to NAV Market region field

force-app/main/default/flows/Task.flow-meta.xml
Updated formula so also runs if date is in the future, prev. it only fired if blank
=> Updated Processbuilder Task

force-app/main/default/objectTranslations/Account-no/TAG_Last_completed_activity_date__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/TAG_Last_completed_activity_date__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added formula for last activity date on acccount, sets date to today if date is in the futre. Needed as future events counst towards std. field
=> Custom last activity date on account

force-app/main/default/permissionsets/Admin_Base.permissionset-meta.xml
Added access to Region and Unit on Task & Event
=> Updated Arbeidsgiver base permset

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
Added field inq. cat 2 on pagelayout
=> Updated fields for related list custom opp. on account

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
- Contact related list changed from enhanced list to Basic list
- Removed Source column from Contact related list
=> Contact related list set to Basic list

force-app/main/default/objects/Account/compactLayouts/EmployerCompactLayout.compactLayout-meta.xml
Reverts navikt/crm-arbeidsgiver-base#771
=> Revert "Delete EmployerCompactLayout.compactLayout-meta.xml"

force-app/main/default/objectTranslations/Account-no/TAG_Is_My_NAV_Market_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/TAG_Is_My_NAV_Market_Region__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added formula field for market region on account
=> Market region on Account

force-app/main/default/reportTypes/Kontoer_med_eller_uten_kontakter.reportType-meta.xml, force-app/main/default/reportTypes/Kontoer_med_eller_uten_kontaktpersponer_fra_NAV.reportType-meta.xml, force-app/main/default/reportTypes/Kontoer_uten_kontaktpersponer_fra_NAV.reportType-meta.xml, force-app/main/default/reportTypes/Muligheter_med_konto_og_NAV_Kontor.reportType-meta.xml, force-app/main/default/reportTypes/TAG_Permitteringsvarsler_med_konto_og_NAV_kontor.reportType-meta.xml
To include custom fields my nav market region
=> Updated custom report types

force-app/main/default/objects/Activity/fields/TAG_service__c.field-meta.xml
Renamed IPS Serivce on task to  (Jobbspesialist)
=> Renamed IPS Service

force-app/main/default/objects/Activity/fields/TAG_service__c.field-meta.xml
Reverts navikt/crm-arbeidsgiver-base#794
Må gjøre på nytt uten å endre API navn
=> Revert "Renamed IPS Service"

force-app/main/default/objects/Activity/fields/TAG_service__c.field-meta.xml
Changed name on picklist values
=> Update IPS service on acctivity

force-app/main/default/objects/Contract__c/fields/NAV_Office__c.field-meta.xml
So it shows NAB unit name ant not ID
=> Changed formula field custom contract

force-app/main/default/objects/TemporaryLayoff__c/fields/TAG_IsMyMarketRegion__c.field-meta.xml
Update of my marketregion formula temp layoff, did not return correrct value
=> Update of my marketregion formula temp layoff

force-app/main/default/objects/Activity/fields/TAG_service__c.field-meta.xml
=> Updated picklist value on Activity field Service

force-app/main/default/objectTranslations/Account-no/TAG_Ultimate_Parent_Account__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/TAG_Ultimate_Parent_Account__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Formula field that shows ulitmate parent on accounts
=> Ultimate parent id formula field

force-app/main/default/objects/CustomOpportunity__c/listViews/Mine_muligheter.listView-meta.xml
=> Lagt til felt i liste Mine Muligheter

force-app/main/default/objects/Account/fields/TAG_Activities_on_sub_accounts__c.field-meta.xml, force-app/main/default/objects/CustomOpportunity__c/listViews/Mitt_NAV_kontor.listView-meta.xml
Updated id to report in formula field on account and updated listveiw on custom opportunity for Mitt NAV kontor
=> Update formule and liste view

force-app/main/default/permissionsets/Arbeidsgiver_opportunity.permissionset-meta.xml
=> Updated permset for Mulighet

force-app/functionality/activities/layouts/Task-TAG Task Layout.layout-meta.xml
Made due data mandatory on tag task page layout
=> Duedata mandatory on pagalayout

force-app/main/default/flexipages/TAG_ContactRecordPage.flexipage-meta.xml, force-app/main/default/layouts/Contact-TAG Contact Layout.layout-meta.xml
Added related list for custom opp, contracts, temp layoff on contact page
=> Added related lists to contact

force-app/main/default/flexipages/TAG_ContactRecordPage.flexipage-meta.xml
=> Contact pagelayout

force-app/main/default/objectTranslations/Account-no/Account_18_ID__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/Account_18_ID__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added field with 18digit ID on account
=> Added field with 18digit ID on account

force-app/main/default/objectTranslations/Account-no/Account-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/Add_to_Custom_Campaign__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/Add_to_Custom_Campaign__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Kampanje.permissionset-meta.xml
Field uses in order to specify account for campaign
=> New field on Account add to custom campaign

force-app/main/default/permissionsetgroups/Arbeidsgiver_Base_Group.permissionsetgroup-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Admin_kampanje.permissionset-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Kampanje.permissionset-meta.xml
Removed CRED from Arbeidsgiver Kampanje, addee new for admin kampanje. Arbeidsgier kampane is now part of base perm set
=> Updated permset for custom campagin

force-app/main/default/permissionsets/Arbeidsgiver_Kampanje.permissionset-meta.xml
Added permissons to is my nav unit, is my nav region and is contacted
=> Updated permset for Arbeidsgiver Kampanje

force-app/main/default/permissionsetgroups/Arbeidsgiver_Base_Group.permissionsetgroup-meta.xml
Added permset for create and share reportfolders to arb. giv. base group permset
=> Added create reportfolders to base

force-app/main/default/prompts/Underskelseinkludering.prompt-meta.xml
=> In app guidance

force-app/main/default/objects/CustomCampaignMember__c/validationRules/Status_ikk_gyldig_for_kampanje.validationRule-meta.xml
Validation rule to only use correct values for Status on sommerjobb kampanje
=> Validation rule on camapagin memeber

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
Updated related list for temp layoffs to inlcude startdate.
=> Updated relatedlist on Account

force-app/main/default/layouts/CustomCampaignMember__c-Custom Campaign Member Layout.layout-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/CustomCampaignMember__c.object-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/listViews/All.listView-meta.xml
Updated listvidews and made account and NAV unit mandatory on page layout.
=> Custom Campaign memeber

force-app/main/default/objects/Contract__c/fields/TAG_Category__c.field-meta.xml
=> Added picklistfield on custom contract

force-app/main/default/objects/Account/listViews/Org_Account_Hierarchy.listView-meta.xml
Now includes number of employees
=> Updated view of Account Hierarchy

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml, force-app/main/default/objectTranslations/Account-no/Shipping_State__c.fieldTranslation-meta.xml, force-app/main/default/objects/Account/fields/Shipping_State__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added shipping state to accountpagelayout
=> Added formula field on account

force-app/main/default/permissionsets/Admin_Base.permissionset-meta.xml
Added acces to NAV Unit on account in admin base permset
=> Added acces to NAV Unit on account in admin base permset

force-app/main/default/objectTranslations/Absence__c-no/TAG_Main_Industry__c.fieldTranslation-meta.xml, force-app/main/default/objects/Absence__c/fields/TAG_Main_Industry__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Sykefravaer.permissionset-meta.xml
Added absence primary industry formula field
=> Sykefraværhovenæring

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/objects/Account/fields/WarningFormattedText__c.field-meta.xml
=> Updated warning text

force-app/functionality/activities/layouts/Event-TAG Event Layout.layout-meta.xml, force-app/functionality/activities/layouts/Task-TAG Task Layout.layout-meta.xml
=> Service mandatory on paglayout

force-app/main/default/permissionsets/Arbeidsgiver_Abonnere_p_kontrollpanel.permissionset-meta.xml
Addes perm set for user to subscribe to dashboards and add users subsribe
=> Permission set subcribe to dashboard

force-app/main/default/objects/Account/fields/WarningFormattedText__c.field-meta.xml
=> Upadet text on employer warning

force-app/functionality/arenaActivity/layouts/ArenaActivity__c-Arena Aktivitet Layout.layout-meta.xml, force-app/main/default/objectTranslations/ArenaActivity__c-no/ArenaActivity__c-no.objectTranslation-meta.xml, force-app/main/default/objects/ArenaActivity__c/fields/Account__c.field-meta.xml, force-app/main/default/objects/ArenaActivity__c/fields/NAVIdent__c.field-meta.xml, force-app/main/default/objects/ArenaActivity__c/fields/NAV_Kontor__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_arenaActivity.permissionset-meta.xml
* Changed label name
* Added Nav ident field perm set
=> Edit Arena Aktivitet object

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Only vissible for profile: NAV Kontaktsenter (Sanitized)
=> Hide LWC externaldata

force-app/main/default/flows/Update_Ansvarlig.flow-meta.xml, force-app/main/default/objects/Activity/fields/Ansvarlig__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml
Added flow that updates "Ansvarlig" with first name and last name of owner. This to be able to search in listview of tasks
=> Søk i oppgaveliste

force-app/main/default/objectTranslations/Account-no/WarningDate__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/WarningFormattedText__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/WarningNote__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/WarningRegisteredBy__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/WarningRemovalDate__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/Account-no/Warning__c.fieldTranslation-meta.xml
Updated translation from Varsel to Merknad
=> Updated translation for warning/varsel on account

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
Updated from Varsel to Merknad
=> Changed header Account

force-app/main/default/layouts/CustomCampaignMember__c-Custom Campaign Member Layout.layout-meta.xml
=> Added keyfield to pagelayout

force-app/main/default/layouts/CustomCampaignMember__c-Custom Campaign Member Layout.layout-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/AccountSentral__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Industry_Code__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Industry__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Main_Industry__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Municipality__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Number_of_Employees__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/CustomCampaignMember__c-no.objectTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Responsible__c.fieldTranslation-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Account_Industry_Code__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Account_Industry__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Account_Main_Industry__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Account_Municipality__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Account_Number_of_Employees__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/Responsible__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Kampanje.permissionset-meta.xml, force-app/main/default/reportTypes/Bedriftskampanjemedlemmer_med_Konto.reportType-meta.xml, force-app/main/default/reportTypes/Kampanjer_med_kontoer_og_kontakter.reportType-meta.xml, force-app/main/default/reportTypes/Kontakter_i_kampanje.reportType-meta.xml
Formula fields related to Account
Updated pagelayout
Translations
Permset
=> Updated Custom Campaignmembe

force-app/main/default/objectTranslations/CustomCampaignMember__c-no/Account_Number_of_Employees__c.fieldTranslation-meta.xml
=> Translate CCM

force-app/main/default/objects/CustomCampaignMember__c/validationRules/Status_ikk_gyldig_for_kampanje.validationRule-meta.xml
Updated to reflect BU statuses
=> Updated Validation rule on custom campaignmemeber

force-app/main/default/objects/CustomCampaignMember__c/validationRules/Status_ikk_gyldig_for_kampanje.validationRule-meta.xml, force-app/main/default/reports/POArbeidsgiverRapporter/New_Activities_with_Accounts_Report_SFC.report-meta.xml
Oppdater rapport aktiviteter knyttet til kontohirarki
=> Activitiesonsubac

force-app/main/default/objects/CustomCampaignMember__c/validationRules/Status_ikk_gyldig_for_kampanje.validationRule-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1147
=> Revert "Statusbu"

force-app/main/default/applications/TAG_NAV_default.app-meta.xml, force-app/main/default/flexipages/TAG_DefaultHomePage.flexipage-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/validationRules/Status_ikk_gyldig_for_kampanje.validationRule-meta.xml
=> Fjerne varsler fra homepage

force-app/main/default/quickActions/CustomCampaignMember__c.Update_Status.quickAction-meta.xml
Update labelname for quick action
=> Changed label CCM

force-app/main/default/flexipages/TAG_ContractDefaultRecordPage.flexipage-meta.xml
Updated transaltions on section headers
=> Update to contract pagelayout

force-app/main/default/permissionsets/Arbeidsgiver_Admin_kampanje.permissionset-meta.xml
Added force update on account to permset
=> Added force update

force-app/main/default/permissionsets/Arbeidsgiver_KampanjeLokal.permissionset-meta.xml
Added share listview permission
=> Updated Lokal Kampanje permset

force-app/functionality/arbeidsplassen/objects/JobPosting__c/compactLayouts/JobPostingCompact.compactLayout-meta.xml, force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/SourceURL__c.field-meta.xml, force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Status__c.field-meta.xml
Changed field type
Added picklist values
=> Field updates

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Show only if user company contains : IT-AVDELINGEN
=> Added filter to show jobposting

force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Expire_Date__c.field-meta.xml, force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Published_Date__c.field-meta.xml, force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/objectTranslations/JobPosting__c-no/Expire_Date__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/JobPosting__c-no/Expires__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/JobPosting__c-no/ProfessionCategory__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/JobPosting__c-no/Published_Date__c.fieldTranslation-meta.xml, force-app/main/default/permissionsets/ArbeidsgiverStillinger.permissionset-meta.xml
Added two formula fields on jobposting, updated page on account for jobpostings
=> Updated jobpostings on pagelayout

force-app/main/default/customPermissions/POAG_Pilot.customPermission-meta.xml, force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/permissionsets/ArbeidsgiverStillinger.permissionset-meta.xml
Added custom persmission for POAG Pilot and assigned to permset Stillinger
=> Custom permission POAG

force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Linkt_to_Rekrutteringsbistand__c.field-meta.xml, force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/objectTranslations/JobPosting__c-no/Linkt_to_Rekrutteringsbistand__c.fieldTranslation-meta.xml, force-app/main/default/permissionsets/ArbeidsgiverStillinger.permissionset-meta.xml, force-app/main/default/reportTypes/Stillinger_med_arbeidsgiver.reportType-meta.xml
On jobposting object and added to accountpagelayout and permset for stillinger
=> Added link to rekrutteringsbistand

force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Is_My_NAV_Unit__c.field-meta.xml
=> Updated formula on is mynavunit

force-app/main/default/flexipages/TAG_DefaultHomePage.flexipage-meta.xml, force-app/main/default/objects/JobPosting__c/listViews/Nye_direktemeldte_stillinger_mitt_kontor.listView-meta.xml
Added "Direktemeldte stillinger mitt kontor" on homepage
=> Added direktemeldte stillinger homepage

force-app/main/default/flexipages/TAG_DefaultHomePage.flexipage-meta.xml, force-app/main/default/objects/JobPosting__c/listViews/Nye_direktemeldte_stillinger_mitt_kontor.listView-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1303
=> Revert "Listviewdirektemeldtestillinger"

force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Is_My_NAV_Unit__c.field-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1306
=> Revert "Updated formula ismynav on jobposting"

force-app/functionality/arbeidsplassen/objects/JobPosting__c/fields/Is_My_NAV_Unit__c.field-meta.xml
Updated formula for is my nav office
=> Updated formula job posting

force-app/main/default/objects/JobPosting__c/listViews/Direktemeldte_stillinger_mitt_kontor.listView-meta.xml
Listview Direktemeldte stilinger mitt nav kontor
=> Listview Direktemeldte stilinger mitt nav kontor

force-app/main/default/objects/Contract__c/fields/TAG_Status__c.field-meta.xml
Added "Avsluttet" as status on custom contract object
=> Added status value

force-app/main/default/objectTranslations/NavTask__c-no/Overdue__c.fieldTranslation-meta.xml, force-app/main/default/objects/NavTask__c/fields/Overdue__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_NavTask.permissionset-meta.xml
Added overdue sign on navtask and added to listview.
=> Added Overdue sign on NAV TASK

force-app/main/default/objects/NavTask__c/listViews/Mitt_NAV_kontor.listView-meta.xml
Updated filter on listeview for navtask, arbeidsgiver my office
=> Updated listview NAV task

force-app/functionality/customOpportunity/layouts/CustomOpportunity__c-Inclusion Page Layout.layout-meta.xml, force-app/main/default/customindex/Contract__c.ExternalId__c.indx-meta.xml, force-app/main/default/objects/Contract__c/fields/ExternalId__c.field-meta.xml
Removed short description on pagelayout Cust Opp
=> Removed short description on pagelayout Cust Opp

force-app/main/default/permissionsets/Arbeidsgiver_Create_and_share_Dashboards.permissionset-meta.xml
Edit permset for create and share report folder and new to create Dashboards
=> Permset Report and DB

force-app/main/default/flows/Add_Account_team_member_fro_FIA_Owner.flow-meta.xml
Updated record type on account to match prod and activated flow
=> Update Account Team with FIA owner

force-app/main/default/flows/Add_Account_team_member_fro_FIA_Owner.flow-meta.xml
Rule to run on change on fia status, not fia owner
=> Update flow update account teamember

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Moved IA informaation to new tab
=> IA tab on account

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Replaced with dynamic list to show recordtype Bedriftsavtale
=> Update contract on accountpage layout

force-app/main/default/objectTranslations/CustomCampaignMember__c-no/TAG_Is_my_market_region__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/CustomCampaignMember__c-no/TAG_Market_Region__c.fieldTranslation-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/TAG_Is_my_market_region__c.field-meta.xml, force-app/main/default/objects/CustomCampaignMember__c/fields/TAG_Market_Region__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Kampanje.permissionset-meta.xml, force-app/main/default/reportTypes/Bedriftskampanjemedlemmer_med_Konto.reportType-meta.xml, force-app/main/default/reportTypes/Kampanjer_med_kontoer_og_kontakter.reportType-meta.xml, force-app/main/default/reportTypes/Kontakter_i_kampanje.reportType-meta.xml
Added marketregion functionality on custom campaign memeber
=> Added Marketregion Custom Camp. memeber

force-app/functionality/arbeidsplassen/objects/JobPosting__c/JobPosting__c.object-meta.xml
=> Search layout job postings

force-app/main/default/permissionsets/Arbeidsgiver_contract.permissionset-meta.xml
Updatet permset to not include view all and modify all on permset
=> Update permset Arbeidsgiver - Kontrakt

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
=> Set sharing to private

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
In order to force update later
=> Bump sharing to ReadWrite

force-app/main/default/sharingRules/Contract__c.sharingRules-meta.xml
Set sharing to share record type Employer Agreement with all NAV Employers group
=> Updated Shering settings contract

.sf/config.json, force-app/main/default/objects/ArenaActivity__c/ArenaActivity__c.object-meta.xml, force-app/main/default/objects/ArenaActivity__c/webLinks/Se_alle_i_alle_enheter.webLink-meta.xml
Link to report to show all for org. hir.
=> Added button on Arena Act.

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
Both Ligtning and pagelayout for TAG layouts
=> Removed temp layouf from pages

force-app/components/bankAccountNumberViewer/lwc/bankAccountNumberViewer/bankAccountNumberViewer.html, force-app/components/bankAccountNumberViewer/lwc/bankAccountNumberViewer/bankAccountNumberViewer.js
bank Account section no longer closes when clicked
=> Removed Bug

force-app/main/default/permissionsets/Arbeidsgiver_Admin_Permissions.permissionset-meta.xml
Now inclueds only custom permission POAG Pilot
=> Permest for arbeidsgiver admins

force-app/main/default/permissionsets/Arbeidsgiver_Backup.permissionset-meta.xml, force-app/main/default/sharingRules/Contract__c.sharingRules-meta.xml
=> Permset Backup

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/flows/TAG_Contact_update_left_company.flow-meta.xml, force-app/main/default/objectTranslations/Contact-no/TAG_Left_Company__c.fieldTranslation-meta.xml, force-app/main/default/objects/Contact/fields/TAG_Left_Company__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_base.permissionset-meta.xml, force-app/main/default/reportTypes/Kontakter_i_kampanje.reportType-meta.xml, force-app/main/default/reportTypes/Kontakter_med_Arbeidsgivere_som_har_Arena_Aktivite.reportType-meta.xml, force-app/main/default/reportTypes/Kontoer_med_eller_uten_kontakter.reportType-meta.xml
=> Employeeleftfunctions

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
=> Corrected misspelling

force-app/main/default/layouts/Contract__c-Measure agreement.layout-meta.xml, force-app/main/default/objectTranslations/Contract__c-no/Sent_Welcome_Message__c.fieldTranslation-meta.xml, force-app/main/default/objects/Contract__c/fields/Sent_Welcome_Message__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Admin_kampanje.permissionset-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_Backup.permissionset-meta.xml
Set that welcome sms to employer has been sent.
=> Added checkbox on contract_C

force-app/functionality/arbeidsplassen/objects/JobPosting__c/JobPosting__c.object-meta.xml, force-app/main/default/reportTypes/Stillinger_med_arbeidsgiver.reportType-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1567
=> Revert "Disable activity on jobposting object"

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, sfdx-project.json
Reverts navikt/crm-arbeidsgiver-base#1677
Skapte feilmeldinger i prod, så tar revert på denne.
=> Revert "Gosys dokumentasjon component"

force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, force-app/main/default/flows/TAG_Update_Partner_Status.flow-meta.xml
Updated flow for updating strategisk partner and added list on account page
=> Updated flow and pagelayout

force-app/main/default/customPermissions/TAG_Dialogueonaccount.customPermission-meta.xml, force-app/main/default/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Vissible with ustom permission
=> Added section for dialogue on accountpage

force-app/main/default/flexipages/IA_Case_Record_Page.flexipage-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1825
=> Revert "Upated IA Case layhout for mobile"

force-app/main/default/flexipages/IA_Case_Record_Page.flexipage-meta.xml
Added filter to hide custom timeline on mobile
=> Adde filter to hide on mobile

.prettierrc, package-lock.json, package.json, sfdx-project.json
Plaforce anbefaler og oppdatere til version 3. Fulgt stegene beskrevet her: https://navikt.github.io/platforce-doc/reference/linting/prettier/
=> Oppdatert prettier som beskrevet av platforce team

force-app/unpackagable/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1834
=> Revert "Related list contact"

force-app/components/bankAccountNumberViewer/customMetadata/API_Base_Configuration.KONTOREGISTER_BASE.md-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1847
=> Revert "Update API_BASE_configuration.KONTOREGISTER_BASE for gcp"

force-app/components/bankAccountNumberViewer/customMetadata/API_Base_Configuration.KONTOREGISTER_BASE.md-meta.xml
Reverts navikt/crm-arbeidsgiver-base#1881
=> Revert "Update API_Base_Configuration.KONTOREGISTER_BASE.md-meta.xml"

force-app/main/default/objectTranslations/IACooperation__c-no/CooperationLastModified__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/IACooperation__c-no/PlanLastModified__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/IACooperation__c-no/PlanLastPublished__c.fieldTranslation-meta.xml, force-app/main/default/objectTranslations/IACooperation__c-no/PlanStatus__c.fieldTranslation-meta.xml, force-app/main/default/objects/IACooperation__c/fields/CooperationLastModified__c.field-meta.xml, force-app/main/default/objects/IACooperation__c/fields/PlanStatus__c.field-meta.xml, force-app/main/default/permissionsets/Arbeidsgiver_IA.permissionset-meta.xml
Changes related to additional fields that will be added in IA Samarbeidsplan json message.
Added field on IACooperation: Plan Status (picklist) and Cooperation Last Modified (date/time).
Added picklist value SLETTET on IA Subtheme Status.
Added permissions for new fields and object translations.
=> Additional fields on IA objects

force-app/components/standaloneNewTimelineActivity/lwc/standaloneNewTimelineActivity/standaloneNewTimelineActivity.html, force-app/components/standaloneNewTimelineActivity/lwc/standaloneNewTimelineActivity/standaloneNewTimelineActivity.js, force-app/main/default/objectTranslations/Account-no/Account-no.objectTranslation-meta.xml, force-app/unpackagable/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml
- Fixed navigation issue where page was redirected to the new activity instead of the account. 
- Fixed layout issue where button group didn't fit on mobile screen by replacing button group with regular buttons.
- Renamed js-file to have same name as component.
- Added translation for account quick action.
- Removed flexi page filter that only displayed button to admin users.
=> New activity button

force-app/components/accountMessages/classes/AccountMessagesController.cls, force-app/components/accountMessages/classes/AccountMessagesWrapper.cls, force-app/components/accountMessages/lwc/accountMessages/accountMessages.html, force-app/components/accountMessages/lwc/accountMessages/accountMessages.js
Samlet funksjoner i LWC komponentet som henter data via controller i felles loadData metode, slik at data hentes i samme transaksjon og antall queries reduseres.
Endret fra aura public til testVisible private på metoder som ikke ble brukt i komponentet.
Lagt til logging av feil dersom det ikke finnes konkursbo.
Lagt til kommentarer.
Forenklet kode og fjernet ubrukt kode.
=> Optimalisering av account messages

force-app/main/default/uiFormatSpecificationSets/Icon_when_J_type.uiFormatSpecificationSet-meta.xml, force-app/unpackagable/flexipages/TAG_EmployerDefaultRecordPage.flexipage-meta.xml, sfdx-project.json
Added dynamic highlights panel with new conditional formatting. Updated project api version to support conditional formatting.
=> Updated account highlights panel

force-app/main/default/reports/POArbeidsgiverRapporter/Sykefravr_p_virksomheten_DBu.report-meta.xml
=> Updated label position on Graph in report

force-app/main/default/layouts/Account-TAG Virksomhet.layout-meta.xml
Endret rekkefølge på related lists.
=> Update Account-TAG Virksomhet.layout-meta.xml

force-app/components/accountBadges/lwc/accountBadges/accountBadges.html, force-app/components/accountMessages/lwc/accountMessages/accountMessages.html, force-app/functionality/amplitude/lwc/amplitudeHome/amplitudeHome.html, force-app/functionality/amplitude/lwc/amplitudeKontoOversikt/amplitudeKontoOversikt.html, force-app/functionality/amplitude/lwc/amplitudeNavUnit/amplitudeNavUnit.html, force-app/functionality/amplitude/lwc/amplitudeNavUnitDetaljer/amplitudeNavUnitDetaljer.html, force-app/functionality/amplitudeUtility/lwc/amplitudeDeviceReader/amplitudeDeviceReader.html
Added tag to remove default margin added around components in flexi pages.
<div style="margin-bottom: calc(var(--lwc-cardSpacingMargin) * -1)"></div>
=> Negative margin tag

force-app/main/default/classes/BadgeConfigProvider.cls, force-app/main/default/classes/BadgeService.cls, force-app/main/default/classes/BadgeServiceTest.cls, force-app/main/default/lwc/relatedRecordsTable/relatedRecordsTable.html
Fikset kolonner på badgePage som går utenfor.
Støtter TYPEOF Owner i query.
=> Format på table og Owner felt

force-app/components/userOfficeHeader/lwc/tagUserOfficeHeader/tagUserOfficeHeader.html, force-app/main/default/aura/homeWithDoubleHeader/homeWithDoubleHeader.cmp
Fjernet bakgrunn på header komponent og la til i aura template i stedet. Eget ikon for unit.
=> Endringer på header og bakgrunn

documentation/Brukerfeedback.md, force-app/main/default/lwc/requestUserFeedback/requestUserFeedback.html, force-app/main/default/lwc/requestUserFeedback/requestUserFeedback.js, force-app/main/default/lwc/requestUserFeedback/requestUserFeedback.js-meta.xml
Property for melding dersom tommel ned.
Justert logikk for å vise ulik melding basert på svar. Fjernet ubrukt kode og oppdatert dokumentasjon.
=> Viser ulike meldinger for tommel opp/ned
